### ISSUE TITLE
Option to set cookie header manually

### ISSUE THREAD

**Issue by JaniSorsa** [FrendsPlatform/Frends.Web#27]
Normally if you set a "Cookie" header it is ignored, but that's because `HttpClientHandler` defaults to using its `CookieContainer` property for cookies. In most cases if Cookies are used, we want to be able to set the "Cookie" header manually.

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.usecookies

**Comment by EkiH** [comment]
Merged in #32
